---
- name: Force delete VM
  ansible.builtin.shell: qm destroy {{ ubuntu_2004_stage_0_id }}
  ignore_errors: True

- name: Create stage 0 VM
  ansible.builtin.shell: qm create {{ ubuntu_2004_stage_0_id }} --memory 2048 --net0 virtio,bridge=vmbr0

- name: Import ubuntu cloud image to stage 0 VM
  ansible.builtin.shell: qm importdisk {{ ubuntu_2004_stage_0_id }} {{ ubuntu_cloud_image_path }} local-lvm

- name: Config stage 0 VM
  ansible.builtin.shell: |
    qm set {{ ubuntu_2004_stage_0_id }} --scsihw virtio-scsi-pci \
    --scsi0 "local-lvm:vm-{{ ubuntu_2004_stage_0_id }}-disk-0" \
    --ide2 "local-lvm:cloudinit" \
    --boot c --bootdisk scsi0 \
    --serial0 socket --vga serial0

- name: Increase boot disk size
  ansible.builtin.shell: qm resize {{ ubuntu_2004_stage_0_id }} scsi0 +5G

- name: Convert vm to stage 0 template
  ansible.builtin.shell: qm template {{ ubuntu_2004_stage_0_id }}
